DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS posts;

CREATE TABLE items (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    url TEXT NOT NULL,
    latestprice REAL DEFAULT 0.0,
    lowprice REAL DEFAULT 0.0, 
    notes TEXT

);
